import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useCart } from '../cart/CartProvider.jsx';
import { useCheckout } from '../checkout/useCheckout.js';
import { money } from '../utils/format.js';
import OrderConfirmDialog from '../components/OrderConfirmDialog.jsx';
export default function CartPage() {
  const cart = useCart(); const navigate = useNavigate(); const [confirm, setConfirm] = useState(false);
  const checkout = useCheckout((order) => navigate('/order-success', { replace: true, state: { order } }));
  return <><div className="page-heading"><span className="eyebrow">YOUR SELECTION</span><h1>장바구니</h1><p>맛있는 선택을 한 번 더 확인해 주세요.</p></div>{cart.uncertain && <div role="alert" className="error">접수 여부를 확인할 주문이 있어요. 중복 주문을 피하려면 먼저 <Link to="/orders" data-testid="cart-check-orders-link">주문 내역을 확인해 주세요.</Link></div>}{!cart.items.length ? <div className="empty"><span className="empty-icon" aria-hidden="true">＋</span><h2>장바구니가 비어 있어요</h2><p>마음에 드는 메뉴를 담아보세요.</p><Link to="/" className="primary button-link" data-testid="cart-menu-link">메뉴 고르기</Link></div> : <div className="cart-layout"><section className="cart-items"><div className="section-heading"><h2>담은 메뉴 <span className="muted">{cart.count}</span></h2><button disabled={checkout.busy || cart.uncertain} onClick={() => cart.dispatch({ type: 'clear' })} data-testid="cart-clear-button">전체 비우기</button></div>{cart.items.map((item) => <article className="cart-row" key={item.menu_item_id}><div><h3>{item.name}</h3><p className="muted">{money(item.unit_price)}</p></div><div className="quantity"><button disabled={checkout.busy || cart.uncertain} onClick={() => cart.dispatch({ type: 'quantity', id: item.menu_item_id, quantity: item.quantity - 1 })} aria-label={`${item.name} 수량 줄이기`} data-testid={`cart-decrease-${item.menu_item_id}`}>−</button><span aria-label={`${item.name} 수량`}>{item.quantity}</span><button disabled={checkout.busy || cart.uncertain || item.quantity >= 999} onClick={() => cart.dispatch({ type: 'quantity', id: item.menu_item_id, quantity: item.quantity + 1 })} aria-label={`${item.name} 수량 늘리기`} data-testid={`cart-increase-${item.menu_item_id}`}>+</button></div><strong>{money(item.unit_price * item.quantity)}</strong><button disabled={checkout.busy || cart.uncertain} aria-label={`${item.name} 삭제`} onClick={() => cart.dispatch({ type: 'remove', id: item.menu_item_id })} data-testid={`cart-remove-${item.menu_item_id}`}>×</button></article>)}</section><aside className="order-summary"><h2>주문 금액</h2><div className="total-line"><span>총 {cart.count}개</span><strong>{money(cart.total)}</strong></div><p className="muted small">주문을 확정하면 메뉴를 준비해 드려요.</p><button className="primary full" disabled={checkout.busy || cart.uncertain} onClick={() => setConfirm(true)} data-testid="cart-checkout-button">주문하기 →</button><Link to="/" className="secondary-link" data-testid="cart-more-link">메뉴 더 고르기</Link></aside></div>}{confirm && <OrderConfirmDialog cart={cart} {...checkout} onClose={() => setConfirm(false)} onSubmit={checkout.submit} />}</>;
}
